apiVersion: v1
kind: Pod
metadata:
  name: db-mysql
  labels:
    app: db-mysql
spec:
  containers: 
    - name: db-mysql
    - image: silmarasilva/db_mysql
      ports:
       - containerPort: 3306
      envFrom:
       - configMapRef:
          name: configmap-db
    # env:
    #   - name: MYSQL_ROOT_PASSWORD
    #     valueFrom: 
    #       configMapKeyRef:
    #         name: db-configmap
    #         key: MYSQL_ROOT_PASSWORD


    # env:
    #   - name: "MYSQL_ROOT_PASSWORD"
    #     value: "1234"
    #   - name: "MYSQL_DATABASE"
    #     value: "db_clientes"
    #   - name: "MYSQL_PASSWORD"
    #     value: "1234"


